version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.2
    working_directory: ~/
    steps:
      - run: touch .env
  deploy-prod:
    machine: 
      enabled: true
    steps: 
      - checkout
      - run:
          name: Deploy Over SSH
          command: 
            ssh $SSH_USER@$SSH_HOST
      - run: cd /var/www/test-ci
      - run: git clone https://github.com/abdurrahmanriyad/test-ci-cd.git