version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.2
    working_directory: ~/
    steps:
      - run: touch .env
  deploy:
    docker:
    steps: 
      - run: ssh -oStrictHostKeyChecking=no -v $SSH_USER@$SSH_HOST “./deploy_project.sh”

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          filters:
            branches:
              only:
                - master
          requires:
            - build