version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.2
    working_directory: ~/
    steps:
      - run: touch .env
  deploy:
    machine: 
      enabled: true
    steps: 
      - run:
          name: Deploy Over SSH
          command: 
            ssh $SSH_USER@$SSH_HOST
      - run: cd /var/www; mkdir test